on: [push]
name: build
jobs:
  runhaskell:
    name: F451
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          enable-stack: true
          stack-version: 'latest'
      - run: stack new f451
      - run: stack setup
      - run: stack build
      - run: stack test

